buffer_size: 100000
tau_theta: 0.05
batch_size: 32
beta: 5
gradient_steps: 10
hidden_dim: 512
learning_rate: 0.00003
learning_starts: 50000
target_update_interval: 10000
tau: 1.0
train_freq: 4
num_nets: 2
aggregator: 'max'
max_grad_norm: 10