batch_size: 128
beta: 0.15
tau_theta: 0.025
gradient_steps: 4
hidden_dim: 128
learning_rate: 0.0032
learning_starts: 0
target_update_interval: 10
tau: 1.0
train_freq: 1
num_nets: 2
aggregator: max
num_nets: 2
max_grad_norm: 10