batch_size: 128
exploration_final_eps: 0.1
exploration_fraction: 0.12
gamma: 0.99
gradient_steps: 3
hidden_dim: 256
learning_rate: 0.001
learning_starts: 0
target_update_interval: 10
train_freq: 1
tau: 1.0
max_grad_norm: 10