aggregator: 'mean'
num_nets: 2
beta: 0.1
batch_size: 256
buffer_size: 1_000_000
gradient_steps: 1
hidden_dim: 256
learning_rate: 0.0003
learning_starts: 10000
target_update_interval: 1
tau: 0.005
train_freq: 1
actor_learning_rate: 0.0001
