batch_size: 64
beta: 1
buffer_size: 10000
gradient_steps: 4
hidden_dim: 64
learning_rate: 0.001
learning_starts: 1000
target_update_interval: 100
tau: 1.0
tau_theta: 0.99
train_freq: 1
num_nets: 2
aggregator: 'mean'