batch_size: 128
beta: 0.1
gamma: 0.995
gradient_steps: 1
hidden_dim: 64
learning_rate: 0.006
learning_starts: 0
target_update_interval: 2
tau: 1.0
train_freq: 1
aggregator: min
num_nets: 2
max_grad_norm: 10
