aggregator: max
batch_size: 64
beta: 0.7
buffer_size: 50000
gradient_steps: 1
hidden_dim: 128
learning_rate: 0.0035
learning_starts: 0
prior_tau: 0.88
prior_update_interval: 5000
target_update_interval: 50
tau: 0.73
tau_theta: 0.76
theta_update_interval: 10
train_freq: 1
