batch_size: 64
beta: 4.5
buffer_size: 30000
gradient_steps: 20
hidden_dim: 64
learning_rate: 0.0005
learning_starts: 0
target_update_interval: 10
tau: 1.0
tau_theta: 0.95
train_freq: 2
num_nets: 2
aggregator: 'max'
prior_tau: 0.005
prior_update_interval: 1
use_rawlik: True