batch_size: 160
beta: 0.05
buffer_size: 30000
gradient_steps: 5
hidden_dim: 64
learning_rate: 0.003
learning_starts: 100
target_update_interval: 400
tau: 1.0
tau_theta: 0.95
train_freq: 1
num_nets: 2
aggregator: 'mean'