aggregator: max
batch_size: 256
beta: 0.015
buffer_size: 50000
gradient_steps: 12
hidden_dim: 32
learning_rate: 0.001
learning_starts: 0
prior_tau: 0.42
prior_update_interval: 500
target_update_interval: 10
tau: 1.0
tau_theta: 0.56
train_freq: 3
