batch_size: 32
buffer_size: 100000
gradient_steps: 1
learning_rate: 0.0001
target_update_interval: 1000
train_freq: 4
learning_starts: 50000
exploration_fraction:  0.1
exploration_initial_eps: 1.0
exploration_final_eps: 0.02
gamma: 0.99
total_timesteps: 10000000
log_freq: 1000