batch_size: 256
beta: 2.5
buffer_size: 100000
gradient_steps: 4
hidden_dim: 64
learning_rate: 0.001
learning_starts: 5000
target_update_interval: 1
tau: 0.02
tau_theta: 0.5
train_freq: 1
num_nets: 2
aggregator: max