batch_size: 32
beta: 8.5
buffer_size: 100000
gradient_steps: 2
hidden_dim: 64
learning_rate: 0.00027
learning_starts: 5000
target_update_interval: 1
tau: 0.06
tau_theta: 0.8
train_freq: 1
num_nets: 2
aggregator: max