batch_size: 256
beta: 0.1
gamma: 0.995
gradient_steps: 4
hidden_dim: 256
learning_rate: 0.0001
learning_starts: 0
target_update_interval: 50
train_freq: 1
gradient_steps: 4
tau: 1.0
aggregator: max
num_nets: 2