aggregator: 'min'
num_nets: 2
beta: 20
batch_size: 64
buffer_size: 1_000_000
gradient_steps: 1
hidden_dim: 256
learning_rate: 0.001
learning_starts: 10000
target_update_interval: 1
tau: 0.005
tau_theta: 0.996
train_freq: 1
actor_learning_rate: 0.0005
