aggregator: 'mean'
num_nets: 2
beta: 1
batch_size: 128
buffer_size: 250_000
gradient_steps: 1
hidden_dim: 256
learning_rate: 0.0002
learning_starts: 0
target_update_interval: 1
tau: 0.003
train_freq: 1
tau_theta: 0.992
actor_learning_rate: 0.0002
