aggregator: 'min'
num_nets: 2
beta: 10
batch_size: 256
buffer_size: 1_000_000
gradient_steps: 1
hidden_dim: 256
learning_rate: 0.0006
learning_starts: 1000
target_update_interval: 1
tau: 0.005
tau_theta: 0.99
train_freq: 1
actor_learning_rate: 0.0002
