aggregator: 'max'
num_nets: 2
beta: 5
batch_size: 256
buffer_size: 50_000
gradient_steps: 1
hidden_dim: 256
learning_rate: 0.002
learning_starts: 0
target_update_interval: 1
tau: 0.05
tau_theta: 0.5
train_freq: 1
actor_learning_rate: 0.0001
