buffer_size: 100000
tau_theta: 0.77
batch_size: 64
beta: 0.53
gradient_steps: 2
hidden_dim: 128
learning_rate: 0.00073
learning_starts: 0
target_update_interval: 1000
tau: 1.0
train_freq: 1
num_nets: 2
aggregator: mean
max_grad_norm: 10