buffer_size: 100000
tau_theta: 0.99
loss_fn: !!python/name:torch.nn.functional.smooth_l1_loss ''
batch_size: 64
beta: 4.07
gradient_steps: 30
hidden_dim: 256
learning_rate: 0.00014
learning_starts: 5000
target_update_interval: 1000
tau: 1.0
train_freq: 5
num_nets: 2