batch_size: 256
buffer_size: 100_000
gradient_steps: 1000
train_freq: 1000
hidden_dim: 128
learning_rate: 0.0003
learning_starts: 10000
target_update_interval: 1
tau: 0.995
tau_theta: 0.0003
actor_learning_rate: 0.0003
