aggregator: 'min'
num_nets: 2
beta: 5
batch_size: 256
buffer_size: 50_000
gradient_steps: 1
hidden_dim: 256
learning_rate: 0.0005
learning_starts: 10000
target_update_interval: 1
tau: 0.001
train_freq: 1
tau_theta: 0.999
actor_learning_rate: 0.00005
